### ISSUE TITLE
Should modifier key trigger reset?

### ISSUE THREAD

**Issue by Riey** [Riey/kime#72]
Like Control, Super, Alt... except for SHIFT it's used for typing characters

**Comment by simnalamburt** [comment]
In Windows default Korean IME and macOS default Korean IME, modifier key does not trigger reset by default. And I think users are used to this behavior.

**Comment by simnalamburt** [comment]
> In Windows default Korean IME and macOS default Korean IME, modifier key does not trigger reset by default. And I think users are used to this behavior.

I retreat my previous comment. Due to lack of wayland protocol's "pre-deactivate notice", it became important to commit strings whenever possible. At least for the wayland, modifier triggering the reset, which is the current implementation, is the preferred behavior.

##### Reference
- https://github.com/korean-input/issues/issues/7

**Comment by Riey** [comment]
I think CJ in CJK use enter to commit their preedit state but Korean acting different from those languages
https://github.com/xdavidwu/wlchewing/blob/8939f4fcce2c9a8b6d70bf83225a85c4c13d137f/im.c#L71
